### ISSUE TITLE
Verify contract tab fails with

### ISSUE THREAD

**Issue by axic** [ewasm/etherchain-light#10]
```
versions is not defined
ReferenceError: versions is not defined
    at /routes/contract.js:13:44
    at Layer.handle [as handle_request] (/node_modules/express/lib/router/layer.js:95:5)
    at next (/node_modules/express/lib/router/route.js:131:13)
    at Route.dispatch (/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/node_modules/express/lib/router/layer.js:95:5)
    at /node_modules/express/lib/router/index.js:277:22
    at Function.process_params (/node_modules/express/lib/router/index.js:330:12)
    at next (/node_modules/express/lib/router/index.js:271:10)
    at Function.handle (/node_modules/express/lib/router/index.js:176:3)
    at router (/node_modules/express/lib/router/index.js:46:12)
```

**Comment by axic** [comment]
And "Upload source" next to the contract code view goes to the same.
