### ISSUE TITLE
Search bar with "t" crashes

### ISSUE THREAD

**Issue by axic** [ewasm/etherchain-light#83]
```
Error: Given input "t" is not a number.
    at Object.numberToHex (/node_modules/web3-utils/src/utils.js:264:15)
    at Method.inputBlockNumberFormatter (/node_modules/web3-core-helpers/src/formatters.js:62:125)
    at /node_modules/web3-core-method/src/index.js:144:38
    at Array.map (<anonymous>)
    at Method.formatInput (/node_modules/web3-core-method/src/index.js:142:32)
    at Method.toPayload (/node_modules/web3-core-method/src/index.js:177:23)
    at Eth.send [as getBlock] (/node_modules/web3-core-method/src/index.js:470:30)
    at async.waterfall.next.name (/routes/block.js:17:16)
    at nextTask (/node_modules/async/dist/async.js:5324:14)
    at Object.waterfall (/node_modules/async/dist/async.js:5334:5)
    at /routes/block.js:15:9
    at Layer.handle [as handle_request] (/node_modules/express/lib/router/layer.js:95:5)
    at next (/node_modules/express/lib/router/route.js:131:13)
    at Route.dispatch (/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/node_modules/express/lib/router/layer.js:95:5)
    at /node_modules/express/lib/router/index.js:277:22
    at param (/node_modules/express/lib/router/index.js:349:14)
    at param (/node_modules/express/lib/router/index.js:365:14)
    at Function.process_params (/node_modules/express/lib/router/index.js:410:3)
    at next (/node_modules/express/lib/router/index.js:271:10)
    at Function.handle (/node_modules/express/lib/router/index.js:176:3)
    at router (/node_modules/express/lib/router/index.js:46:12)
```

**Comment by cdetrio** [comment]
https://github.com/ewasm/etherchain-light/pull/86
